package com.transatron.payroll;

public interface IMProperty {
    String TRON_API_WRAPPER = "TRON_API_WRAPPER";
    String D_CSV_FILE = "D_CSV_FILE";//distribution csv file
    String D_EXPORT_CSV_FILE = "D_EXPORT_CSV_FILE";//distribution csv file to export results to
    String D_DISTRIBUTION_DATA = "D_DISTRIBUTION_DATA";//distribution data
    String APP_STATUS = "APP_STATUS";//READY, WORKING
    String APP_STATUS_MESSAGE = "APP_STATUS_MESSAGE";//READY, WORKING
    String APP_STATUS_PROGRESS = "APP_STATUS_PROGRESS";//READY, WORKING
    String D_USDT_TO_DISTRIBUTE_VALUE = "D_USDT_TO_DISTRIBUTE_VALUE";//text field value
    String MAIN_WALLET_PK = "MAIN_WALLET_PK";
    String MAIN_WALLET_PK_ECRYPTED = "MAIN_WALLET_PK_ECRYPTED";
    String TRON_GRID_API_KEY = "TRON_GRID_API_KEY";
    String TRON_JSONRPC_ENDPOINT = "TRON_JSONRPC_ENDPOINT";
    String TRANSATRON_API_ENDPOINT = "TRANSATRON_API_ENDPOINT";
    String WALLET_BALANCES = "WALLET_BALANCES";
    String WALLET_ADDRESS = "WALLET_ADDRESS";

    String WALLET_QR_CODE = "WALLET_QR_CODE";

    String TT_SERVICE ="TT_SERVICE";

    String TT_MARKET_INFO = "TT_MARKET_INFO";

    String TT_DEPOSIT_ADDRESS = "TT_DEPOSIT_ADDRESS";

    String PROGRAM_ACTION = "PROGRAM_ACTION";
    String PROGRAM_ERROR = "PROGRAM_ERROR";

    String ORDER_DATE_TIME = "ORDER_DATE_TIME";


}
